server:
    port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
          native:
              searchLocations: file:///home/gambit/projects/spmia-my/spmia-my-project/configurationserver/src/main/resources/config/licensingservice